baseURL = 'https://blog.nier.tw/'
defaultContentLanguage = "en"
languageCode = "en"
title = 'Nier'
theme = "dream"

# [services]
# [services.disqus]
# shortname = ""
# [services.googleAnalytics]
# ID = ""

[params]
# zenMode = true

lightTheme = "emerald"
darkTheme = "forest"

# backgroundImage = "me/background.jpg"
# backgroundImageDark = ""

author = "Nier"
# description = ""
avatar = "me/avatar.png"
headerTitle = "Nier"
motto = "ğŸ¹ ğŸµ ğŸ‘¨â€ğŸ’»"

footerBottomText = "ä¸€æ­¥ä¸€æ­¥"

# rss = true

# utterancesRepo = ""

# valine = true
# LEANCLOUD_APP_ID = ""
# LEANCLOUD_APP_KEY = ""

# waline = true
# walineServer = ""

email = "blog@nier.tw"

siteStartYear = 2025

# favicon = "favicon.ico"

# Syntax highlighting
# customSyntaxHighlighting = true

# options
stickyNav = true
# reorderNavItems = ["search", "rss", "posts", "categories", "tags"]
# collapseNavItems = ["posts", "categories", "tags"]
# noDefaultSummaryCover = true
# showTableOfContents = true
# showSummaryCoverInPost = true
# imageZoomableInPost = true
# showPrevNextPost = true
reorderShares = ["x", "facebook"]

# [params.navItems]

# [params.advanced]
# customCSS = ["css/custom.css"]
# customJS = []

# [params.experimental]
# jsDate = true
# jsDateFormat = "yyyyå¹´MMæœˆddæ—¥"